name: innout
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - matplotlib
  - scikit-learn
  - scikit-image
  - pillow
  - jupyter
  - jupyterlab
  - seaborn
  - plotly
  - tqdm
  - pyyaml
  - pip
  - pip:
      - torch
      - torchvision
      - torchaudio
      - timm
      - wandb
      - huggingface-hub
      - safetensors
      - git+https://github.com/fra31/auto-attack
      - absl-py
